stages:
  - build

# Build pdf file
latex:
  image: texlive/texlive:latest
  stage: build
  script:
    # Install inkscape for LaTeX svg package
    - apt-get update -qq && apt-get install --no-install-recommends -y inkscape
    - apt-get autoclean autoremove && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    - latexmk -cd -pdf -shell-escape thesis.tex
  artifacts:
    paths:
      - "thesis.pdf"
    expire_in: 1 day
